[package]
name = "petsclinic-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petsclinic-lib = { path = "../petsclinic-lib" }
cursive = "0.17" #Text user interface
mongodb = "2.1.0"